version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DATABASE_USER=root
      - DB_HOST=db
      - DB_PORT=3306
      - DB_PASSWORD=123456789
      - DB_NAME=tmdb_project
    networks:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: tmdb_project
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:6
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:

